# -*-Makefile-*-

default: main.c pathData.txt
	@echo "dome"

update: lib/
	@echo [updating \"./lib/user_function.h\"]
	@curl https://raw.githubusercontent.com/pritam12426/systme-configuration/main/global/user_c_lib/user_function.h -o ./lib/user_function.h > /dev/null 2>&1
